name: price-clf
channels:
  - conda-forge
dependencies:
  - python=3.9
  - tqdm
  - kaggle
  - click
  - Sphinx
  - coverage
  - pytest
  - flake8
  - python-dotenv>=0.5.1
  - ipykernel
  - jupyterlab
  - jupyter
  - plotly
  - plotnine
  - matplotlib
  - seaborn
  - scikit-learn
  - scipy
  - numpy
  - pandas
  - statsmodels
  - doit
  - nltk
  - regex
  - black
  - wordcloud
  - papermill